= Notice

All libraries imported via Maven are listed automatically in the
respective `NOTICE.txt` files in all modules.

== Pddl Antlr grammar

The Grammar is an updated version of https://github.com/antlr/grammars-v4/blob/master/pddl/Pddl.g4

Original author:
PDDL grammar for ANTLR v3,
Zeyn Saigol,
School of Computer Science,
University of Birmingham

File: `transport-core/src/main/antlr4/com/oskopek/transport/persistence/Pddl.g4`

== Interval Tree

The implementation is an updated version of https://github.com/kevinjdolan/intervaltree

Original author:
Kevin J Dolan

License: MIT

Files in: `transport-thirdparty/src/main/java/com/github/kevinjdolan/intervaltree/`

== Heaps

The implementations is a forked and updated version of the Heaps 2.0 release from: https://code.google.com/archive/p/java-heaps/

Original author:
Fran Lattanzio

License: MIT

Files in: `transport-thirdparty/src/main/java/org/teneighty/heap/`

== GraphStream Algorithm TopologicalSort

The implementations is a forked and updated version of the GraphStream GitHub repository release at: https://github.com/graphstream/gs-algo

Original authors:
The GraphStream team:

- Julien Baudry <julien.baudry@graphstream-project.org>
- Antoine Dutot <antoine.dutot@graphstream-project.org>
- Yoann Pigné <yoann.pigne@graphstream-project.org>
- Guilhelm Savin <guilhelm.savin@graphstream-project.org>


Contributors:

- Frédéric Guinand <frederic.guinand@univ-lehavre.fr>
- Guillaume-Jean Herbiet <guillaume-jean@herbiet.net>

License: LGPL

Files in: `transport-thirdparty/src/main/java/org/graphstream/algorithm/`
