= TransportEditor Manual (EN)
:sectnums:

Welcome to TransportEditor's manual!

TransportEditor is a planning dashboard for the Transport planning domain.
You can use it to study various Transport domain variants,
create, edit and visualize problem instances, after which you can
run various planners and validators and visualize the resulting plans.

How TransportEditor works and what it can do:

. Create a new session, create or load a domain.
. Create/load a problem. TransportEditor will display the road graph for you.
You can use the buttons on the right to edit the graph and its elements.
. Go to "%root.session" -> "%root.setPlanner" to set a planner to use. Likewise, set a validator in
"%root.session" -> "%root.setValidator"
. Click on the "%plan" button to run the planner. After some time, the planning will end and you can
see the generated plan in the table on the right. There are several plan views available, f.e. the Gantt chart.

Now you can edit the graph, the vehicles, packages, rerun your planner and test the outcome. Happy planning!

Read the following sections if you want to learn to work with TransportEditor quickly and effectively.

== Getting help

If you can't find the answer to your question or request in this document
(located in the menu, in "%root.help" -> "%root.help"),
feel free to submit a pull request/issue in
the https://gitlab.com/oskopek/TransportEditor[GitLab repository] of TransportEditor,
post a question on https://stackoverflow.com[StackOverflow], or email me personally.
You can find all the needed information in the menu, in "%root.help" -> "%root.about".

=== Changing the language

If you want to run a translated version of TransportEditor,
set your system locale accordingly and restart TransportEditor.

If you want to try out a translated version (on Linux) without changing your system locale permanently,
try running: `LC_ALL="LOCALE" java -jar TransportEditor.jar`, where `LOCALE` is any locale available on your system
(run `locale -a` to view all available).

TransportEditor currently does not support changing the language on the fly.

== The Transport planning domain

Transport is a domain designed originally for the International Planning Competition
(IPC, part of the International Conference on Automated Planning and Scheduling ICAPS).
Originally, Transport appeared at http://icaps-conference.org/ipc2008/deterministic/Domains.html[IPC-6 2008].
Since then, it has been used in every IPC, specifically http://www.plg.inf.uc3m.es/ipc2011-deterministic/[IPC-7 2011]
and https://helios.hud.ac.uk/scommv/IPC-14/[IPC-8 2014].

There are two basic formulations of the Transport domain family (i.e. two "similar Transport domains"):

* `transport-strips -- the classical, sequential Transport domain. See the STRIPS section below for details.
* `transport-numeric` -- the numerical Transport domain. See the Numeric section below for details.

Both of these formulations have been used interchangeably in various competition tracks.

Short descriptions of the various tracks and subtracks can be found in the rule pages of
https://helios.hud.ac.uk/scommv/IPC-14/rules.html[IPC-6]
and the http://icaps-conference.org/ipc2008/deterministic/CompetitionRules.html[rule page of IPC-8].

As a bonus, TransportEditor supports custom domains based on the Transport domain family.
Users can create new Transport-like domains that have any subset of constraints/features of the two basic formulations.
Only subsets in which individual constraints are not in conflict with each other are allowed.

=== Transport STRIPS formulation description

The STRIPS version of Transport is a logistics domain -- vehicles with limited capacities drive around on
a (generally asymmetric) positively-weighted oriented graph, picking up and dropping packages along the way.
Picking up or dropping a package costs 1, driving along a road costs depending on the edge weight.
All packages have a size of 1. The general aim is to minimize the total cost,
while delivering all packages to their destination.

=== Transport Numeric formulation description

The numerical version of Transport is very similar to the STRIPS version. The key differences are:

* Package sizes can now be any positive number.
* The concept of fuel -- every vehicle has a maximum fuel level, current fuel level,
and all roads have a fuel demand (generally different than the length of the road).
A vehicle can refuel if there is a petrol station at the given location.
Refuelling always fills the vehicle's tank to the max.
* The introduction of time:
** The duration of driving along a road is equal to it's length.
** The duration of picking a package up or dropping it off is equal to 1.
** The duration of refuelling is equal to 10.
** A vehicle cannot pick up or drop packages concurrently -- it always handles packages one at a time.
** A vehicle cannot do other actions during driving to another location
(it is essentially placed "off the graph" for the duration of driving).
* The cost function is removed (we now minimize the total duration of a plan).

== Loading and saving

=== Session

Session is an abstraction over all the user workspace. It encompasses all your currently loaded data and options,
including the domain, problem, plan, planner and validator.

You can create a new session by clicking on "%root.session" -> "%root.new".

Session can be saved to an XML file using "%root.session" -> "%root.save" or "%root.session" -> "%root.saveAs".
After that, you can come back to your session any time by using "%root.session" -> "%root.load", without
having to load all the individual parts again.

=== Domain

Loading a domain from its PDDL file is as simple as clicking on "%root.domain" -> "%root.load".
A file chooser dialog will pop up, where you can select the correct file.

==== Domain variant creator

After clicking on "%root.domain" -> "%root.new", the domain variant creator will help
you adjust the constraints and features available in your domain.
The base of the domain includes a few predicates and functions, along with:

* the graph
* distances of edges
* locatables (packages, vehicles, ...)

And actions:

* Pick up (a package into a vehicle)
* Drop (a package from a vehicle)
* Drive (a vehicle between two nodes on an edge)

Each action has an associated cost, and the minimization function is by default the total cost of a plan.

There two basic domain types you can select:

* Sequential -- All actions are disjunct in time, the total-duration (sum of action durations) is minimized by default.
* Temporal -- Introduces start/end times of actions,
preconditions/effects are now checked with temporal reasoning (at start/at end/over all),
new minimization function -- total-time.

There are several optional constraints you can place on your model:

* absence of capacity (vehicles have no maximum capacity)
* fuel (introduces petrol stations, max fuel capacity of a vehicle and it's current status.
Also introduces an additional edge-weight, fuel-demand -- equally long edges can have different
fuel-demands, for example)
* numerical minimization -- currently not implemented. Sorry for the inconvenience.

You can select any subset of these constraint packages, but only a single cost function to go with them.
The domain variant creator will then create your chosen domain and TransportEditor enables you to export it to PDDL,
so that you can use it in different (mainly domain-independent) planners.

=== Problem

Loading a problem from its PDDL file is as simple as clicking on "%root.problem" -> "%root.load".
A file chooser dialog will pop up, where you can select the correct file.

Saving and creating new problems works quite simply with the appropriate button in the "%root.problem" menu.

=== Plan

Loading a plan from its PDDL file is as simple as clicking on "%root.plan" -> "%root.load".
A file chooser dialog will pop up, where you can select the correct file.

Saving and creating new plans works quite simply with the appropriate button in the "%root.plan" menu.
Plans can also be changed by the planner (see the "%plan" button on the right) and by the user, in the plan view
table at the bottom right -- either by rearranging the plan actions or changing their start time.

=== Demo data

You can try all of this out on the datasets gathered from the IPC competitions, located in the folder `datasets/`.

== Editing the problem

Left-clicking and dragging will move the locations on screen. To attempt a new redraw of the graph,
press the "%redraw" button. If the layout doesn't get redrawn properly, try moving a few nodes from their
positions to destabilize the algorithm and press redraw again.

You can select graph elements by left-clicking and dragging in the graph area, creating a selection region.
The buttons on the right will get enabled/disabled based on the selected elements in the graph.
To be aware of all the selection options, it is recommended to read through the
Shortcut quick-tip manual, located in "%root.about" -> "%root.shortcutQuickTips". To deselect nodes,
press Escape (Esc) or click on point in the graph containing no element.

The "%lock" button disables all graph editing. Clicking it again will unlock the graph.

== Planning

To set a planner, go to the "%root.session" -> "%root.setPlanner" menu.

=== External planners

In the "%root.setPlanner" menu, you can choose to set an external planner. An external planner is either an
executable's name that is present in the filesystem executable path (based on the environment variable PATH)
or directly a path to an executable file.

The planner executable must follow a few rules (usually these are enforced by wrapping your planner in a shell script
that enforces these rules):

* Only the resulting plan is written to standard output.
* All logging, debugging and error messages are written to standard error output.
* The executable must exit with a 0 return code if and only if planning succeeded and a plan was output to stdout.
* The executable must take two filepath parameters -- the domain in PDDL and the problem in PDDL.
** You can specify a parameter template while setting the external planner. For example, you can specify `fast-downard`
to be the executable and its parameters to be `{0} {1} --search "astar(lmcut())"`. The template `{0}` will get
substituted for the domain filename at runtime, the `{1}` will be the problem filename.

=== Internal planners

Unfortunately, TransportEditor does not currently contain any internal planners.

=== Validating your plan

To set a validator, go to the "%root.session" -> "%root.setValidator" menu.

The "%root.setSequentialValidator" is a simple validator used for sequential domains that checks basic
properties of the problem state, like predicates holding before and effects holding after applying an action.
See the class `SequentialValidator` for more detailed information.

==== External validators

In the "%root.setValidator" menu, you can choose to set an external validator. An validator planner is either an
executable's name that is present in the filesystem executable path (based on the environment variable PATH)
or directly a path to an executable file.

The validator executable must follow a few rules:

* All logging, debugging and error messages are written to standard error output or standard output.
* The executable must exit with a 0 return code if and only if the plan is valid.
* The executable must take three filepath parameters -- the domain in PDDL, the problem in PDDL and the plan in a
VAL-like format.
** You can specify a parameter template while setting the external validator.
For example, you can specify `val` to be the executable and its parameters to be `{0} {1} {2}"`.
The template `{0}` will get substituted for the domain filename at runtime, the `{1}` will be the problem filename and
`{2}` will be the plan filename.

== Plan views

On the lower right hand side when a plan is loaded, you can see a table with the plans actions. If the loaded domain
is sequential, that table displays basic action info and its first column is draggable - you can reorder the plan's
actions by dragging them from one place to another in the table. If the domain is temporal, you can double click and
edit the action start time in the table.

Both of these tables are filterable -- if you right click on the table's headers a small dialog popup will show up
and you can choose which values to show and which to hide. These choices will get propagated to the other plan views
and they too will get filtered (if possible).

One of the alternative table views is the Gantt chart. It displays action objects on the Y axis and time on the X axis.
The contents of the chart are individual actions involving the given action objects at the given time. The color
corresponds to a type of action.

== Stepping through a plan

When a plan is loaded, there is an option of stepping through the plan's actions and visualizing the intermediate
problem state. To enable this, press the "%steps.show" button in the panel on the right -- this will remove
all filters in the table and disable graph editing. Do note that stepping through the plan does not change the
actual problem -- if you press "%steps.hide", the original problem will appear.

When stepping through a plan, a new panel will display, showing navigation buttons.
You can move in the plan in three different ways:

* Using the up ("%arrow.up") and down ("%arrow.down") arrow buttons. This will de-apply or apply the previous
or next action in the plan. Do note, that in temporal plans, this might not necessarily be the action
above or beneath the currently selected one, although it probably will be.

* Selecting the appropriate action in the plan table. The plan state will change to before, during or after the
selected action is applied -- depending on which time button is selected ("%time.start", "%time.middle" or "%time.end").

* Selecting a specific time in the text field on the right. You can input any positive number and the plan will move to
that time step. It will either apply the "at start" effects of actions starting at the selected time or not, depending
on the selection of the "%time.applystarts" button. If it is selected, the "at start" effects will be applied.
Otherwise, only "at end" effects of actions ending at the selected time will be applied to the plan state.
